SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

DROP SCHEMA IF EXISTS `news_db` ;
CREATE SCHEMA IF NOT EXISTS `news_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `news_db` ;
DROP TABLE IF EXISTS `news_db`.`news` ;

CREATE TABLE IF NOT EXISTS `news_db`.`news` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `telegram_msg_id` INT NOT NULL,
  `source` VARCHAR(255) NOT NULL,
  `date` DATETIME NOT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `summary` TEXT NULL DEFAULT NULL,
  `text` TEXT NULL DEFAULT NULL,
  `media_file` TEXT NULL DEFAULT NULL,
  `refactoredTitle` VARCHAR(255) NULL DEFAULT NULL,
  `refactoredText` TEXT NULL DEFAULT NULL,
  `resume` TEXT NULL DEFAULT NULL,
  `tags` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

CREATE USER IF NOT EXISTS 'user'@'localhost' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON news_db.* TO 'user'@'localhost';
FLUSH PRIVILEGES;